### ISSUE TITLE
kubernetes dashboard add-on ignores helm_config 

### ISSUE THREAD

**Issue by constantinevitt** [aws-ia/terraform-aws-eks-blueprints#1059]
## Description

The kubernetes dashboard add-on largely ignores `kubernetes_dashboard_helm_config` while having argocd manage the addons. I say "largely" because the following block will create the namespace but not put the resources in it. Additionally, it ignores all values being passed in from the template file.

```
module "eks_blueprints_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons?ref=v4.12.2"

  eks_cluster_id       = "my existing cluster"

  enable_argocd = true
  argocd_manage_add_ons = true

  enable_kubernetes_dashboard         = true
  kubernetes_dashboard_helm_config = {
    name       = "k8s-dashboard"                           # (Required) Release name.
    repository = "https://kubernetes.github.io/dashboard/" # (Optional) Repository URL where to locate the requested chart.
    chart      = "kubernetes-dashboard"                    # (Required) Chart name to be installed.
    version    = "5.10.0"
    namespace  = "kubernetes-dashboard"
    values     = [templatefile("${path.module}/helm_values/kubernetes_dashboard.yaml", {})]
  }
}
```

sample helm values from `${path.module}/helm_values/kubernetes_dashboard.yaml`
```
service:
  type: NodePort
  externalPort: 443

ingress:
  enabled: True
```

## Versions

- Module version [Required]:
v4.12.2
- Terraform version:
v1.3.2
- Provider version(s):
```
Terraform v1.3.2
on linux_amd64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.34.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.9.0
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
```

## Reproduction Code [Required]

See above excerpts; 
Alternatively, use the `gitops/argocd` example and add the following block about kubernetes dashboard
https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/gitops/argocd

```
  enable_kubernetes_dashboard         = true
  kubernetes_dashboard_helm_config = {
    name       = "k8s-dashboard"                           # (Required) Release name.
    repository = "https://kubernetes.github.io/dashboard/" # (Optional) Repository URL where to locate the requested chart.
    chart      = "kubernetes-dashboard"                    # (Required) Chart name to be installed.
    version    = "5.10.0"
    namespace  = "kubernetes-dashboard"
    values     = [templatefile("${path.module}/helm_values/kubernetes_dashboard.yaml", {})]
  }
```

Attempt to include kubernetes dashboard with some customized configuration e.g. different version, namespace, service type, with ingress ect.

## Expected behaviour

Add on installs with customized values. 

## Actual behaviour

Add on installs with defaults.

### Terminal Output Screenshot(s)

```
$ kubectl get namespaces
NAME                   STATUS   AGE
argo-rollouts          Active   19h
argocd                 Active   19h
aws-for-fluent-bit     Active   19h
cert-manager           Active   19h
default                Active   20h
karpenter              Active   19h
keda                   Active   19h
kube-node-lease        Active   20h
kube-public            Active   20h
kube-system            Active   20h
kubernetes-dashboard   Active   32s
team-burnham           Active   17h
team-carmen            Active   17h
team-riker             Active   17h
vpa                    Active   19h
yunikorn               Active   19h

$ kubectl get svc -n kubernetes-dashboard
No resources found in kubernetes-dashboard namespace.

$ kubectl get svc -n kube-system
NAME                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
aws-load-balancer-webhook-service           ClusterIP   <redacted>   <none>        443/TCP         16h
cluster-autoscaler-aws-cluster-autoscaler   ClusterIP   <redacted>     <none>        8085/TCP        17h
kube-dns                                    ClusterIP   <redacted>      <none>        53/UDP,53/TCP   20h
kubernetes-dashboard                        ClusterIP   <redacted>   <none>        443/TCP         26m
metrics-server                              ClusterIP   <redacted>     <none>        443/TCP         17h
```

**Comment by bryantbiggs** [comment]
When provisioning via GitOps/ArgoCD - the values files shown in this repository or even passed in through `helm_config` are not used. The `values.yaml` will sit in your associated GitOps repo where the respective helm chart is located

**Comment by constantinevitt** [comment]
In my use case I want to pass various ingress annotation parameters e.g. private subnet ids, cert arn, ect which I have available during the Terraform deployment phase.

I have a generic cluster deployment module which receives variable values for a different repository, including node groups, names environments, vpc ids ect, this happens to be the same repository which will contain the cluster specific addon customization values and so on. However, I want to be able to pass back cluster and network scoped information back to the helm templates such as load balancer and target group names and arns.

How can I accomplish this?

**Comment by bryantbiggs** [comment]
there are a number of ways, for example you can use https://docs.aws.amazon.com/systems-manager/latest/userguide/integrating_csi_driver.html where Terraform outputs shared/common values to SSM parameters and the kubernetes configs pull those in. You can use the GitHub provider to write a `values.yaml` file to GitHub from Terraform

**Comment by constantinevitt** [comment]
I'm not sure I'm following. Let's take the specific example from above

I need to inform `helm` or `kubectl` that I want want my dashboard to be exposed via ingress which needs to look like this
```
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/load-balancer-name: ${load_balancer_name}
      alb.ingress.kubernetes.io/group.name: ${load_balancer_group_name}
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/target-type: instance
      alb.ingress.kubernetes.io/certificate-arn: ${certificate_arn}
      alb.ingress.kubernetes.io/subnets: ${subnets}
      alb.ingress.kubernetes.io/tags: ${tags}
```

Let's say I write all these parameters to SSM how do I then inject them into the corresponding values file, which will contain other data, in the secondary repository?
