### ISSUE TITLE
Terraform delete/create Karpenter provisioner is very risky

### ISSUE THREAD

**Issue by allamand** [aws-ia/terraform-aws-eks-blueprints#1192]
## Description

I configured my Terraform to create a Karpenter provisioner:

```
data "kubectl_path_documents" "karpenter_provisioners" {
  pattern = "${path.module}/kubernetes/karpenter/*"
  vars = {
    azs                     = join(",", local.azs)
    iam-instance-profile-id = "${local.name}-${local.node_group_name}"
    eks-cluster-id          = local.name
    eks-vpc_name            = local.name
  }
}

resource "kubectl_manifest" "karpenter_provisioner" {
  for_each  = toset(data.kubectl_path_documents.karpenter_provisioners.documents)
  yaml_body = each.value
}
```

<details>
  <summary>You can expand to see the actual provisioner.yaml</summary>

```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: karpenter-default
spec:
  instanceProfile: ${eks-cluster-id}-managed-ondemand
  subnetSelector:
    kubernetes.io/cluster/${eks-cluster-id}: '*'
    kubernetes.io/role/internal-elb: '1'
  securityGroupSelector:
    aws:eks:cluster-name: ${eks-cluster-id}
  tags:
    karpenter.sh/cluster_name: ${eks-cluster-id}
    karpenter.sh/provisioner: team
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those
  # that can't be removed.  Mutually exclusive with the ttlSecondsAfterEmpty parameter.
  consolidation:
    enabled: true
  #sttlSecondsAfterEmpty: 60
  requirements:
    - key: karpenter.k8s.aws/instance-family
      operator: NotIn
      values:
        - a1
        - c1
        - c3
        - inf1
        - t3
        - t2
    - key: karpenter.k8s.aws/instance-cpu
      operator: Lt
      values: 
        - "33"
    - key: 'kubernetes.io/arch'
      operator: In
      values: ['amd64']
    - key: karpenter.sh/capacity-type
      operator: In
      #values: ['on-demand']
      values: ['on-demand', 'spot']
  providerRef:
    name: karpenter-default
    tags:
      karpenter.sh/cluster_name: ${eks-cluster-id}
      karpenter.sh/provisioner: default
  limits:
    resources:
      cpu: '200'
  labels:
    billing-team: default
    team: default
    type: karpenter
  taints:
    - key: karpenter
      value: 'true'
      effect: NoSchedule

```
</details

The problem is that when I update this yaml file and apply again with terraform, then Terraform will delete the object first.
At this time, Karpenter will garbage-delete all ressources created from this object and it can abruptly delete all the Nodes that was created bringing disruption for my application deployed on thoses nodes..

## Expected behaviour

I don't know if terraform can just update/patch the object instead of delete/create, if possible this can be a solution.

If not, we can clearly warn users to not create ressources that way which can leads in cluster disruption in case of deletion.

## Actual behaviour

Actually, Terraform will delete the provisioner and recreate it

```
Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create
  - destroy
```

<details>
  <summary>Terraform will perform the following actions:</summary>
  
```
  # kubectl_manifest.karpenter_provisioner["apiVersion: karpenter.sh/v1alpha5\nkind: Provisioner\nmetadata:\n  name: default\nspec:\n  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those\n  # that can't be removed.  Mutually exclusive with the ttlSecondsAfterEmpty parameter.\n  consolidation:\n    enabled: true\n  #sttlSecondsAfterEmpty: 60\n  requirements:\n    - key: karpenter.k8s.aws/instance-family\n      operator: NotIn\n      values:\n        - a1\n        - c1\n        - c3\n        - inf1\n        - t3\n        - t2\n    - key: karpenter.k8s.aws/instance-cpu\n      operator: Lt\n      values: \n        - \"33\"\n    - key: 'kubernetes.io/arch'\n      operator: In\n      values: ['amd64']\n    - key: karpenter.sh/capacity-type\n      operator: In\n      #values: ['on-demand']\n      values: ['on-demand', 'spot']\n  providerRef:\n    name: karpenter-default\n    tags:\n      karpenter.sh/cluster_name: eks-blueprint\n      karpenter.sh/provisioner: default\n  limits:\n    resources:\n      cpu: '200'\n  labels:\n    billing-team: default\n    team: default\n    type: karpenter\n  taints:\n    - key: karpenter\n      value: 'true'\n      effect: NoSchedule"] will be created
  + resource "kubectl_manifest" "karpenter_provisioner" {
      + api_version             = "karpenter.sh/v1alpha5"
      + apply_only              = false
      + force_conflicts         = false
      + force_new               = false
      + id                      = (known after apply)
      + kind                    = "Provisioner"
      + live_manifest_incluster = (sensitive value)
      + live_uid                = (known after apply)
      + name                    = "default"
      + namespace               = (known after apply)
      + server_side_apply       = false
      + uid                     = (known after apply)
      + validate_schema         = true
      + wait_for_rollout        = true
      + yaml_body               = (sensitive value)
      + yaml_body_parsed        = <<-EOT
            apiVersion: karpenter.sh/v1alpha5
            kind: Provisioner
            metadata:
              name: default
            spec:
              consolidation:
                enabled: true
              labels:
                billing-team: default
                team: default
                type: karpenter
              limits:
                resources:
                  cpu: "200"
              providerRef:
                name: karpenter-default
                tags:
                  karpenter.sh/cluster_name: eks-blueprint
                  karpenter.sh/provisioner: default
              requirements:
              - key: karpenter.k8s.aws/instance-family
                operator: NotIn
                values:
                - a1
                - c1
                - c3
                - inf1
                - t3
                - t2
              - key: karpenter.k8s.aws/instance-cpu
                operator: Lt
                values:
                - "33"
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - on-demand
                - spot
              taints:
              - effect: NoSchedule
                key: karpenter
                value: "true"
        EOT
      + yaml_incluster          = (sensitive value)
    }

  # kubectl_manifest.karpenter_provisioner["apiVersion: karpenter.sh/v1alpha5\nkind: Provisioner\nmetadata:\n  name: default\nspec:\n  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those\n  # that can't be removed.  Mutually exclusive with the ttlSecondsAfterEmpty parameter.\n  consolidation:\n    enabled: true\n  #sttlSecondsAfterEmpty: 60\n  requirements:\n    - key: karpenter.k8s.aws/instance-family\n      operator: NotIn\n      values:\n        - a1\n        - c1\n        - c3\n        - inf1\n        - t3\n        - t2\n    - key: karpenter.k8s.aws/instance-cpu\n      operator: Lt\n      values: \n        - \"33\"\n    - key: 'kubernetes.io/arch'\n      operator: In\n      values: ['amd64']\n    - key: karpenter.sh/capacity-type\n      operator: In\n      values: ['on-demand']\n      #values: ['on-demand', 'spot']\n  providerRef:\n    name: karpenter-default\n    tags:\n      karpenter.sh/cluster_name: eks-blueprint\n      karpenter.sh/provisioner: default\n  limits:\n    resources:\n      cpu: '200'\n  labels:\n    billing-team: default\n    team: default\n    type: karpenter\n  taints:\n    - key: karpenter\n      value: 'true'\n      effect: NoSchedule"] will be destroyed
  # (because key ["apiVersion: karpenter.sh/v1alpha5\nkind: Provisioner\nmetadata:\n  name: default\nspec:\n  # Enables consolidation which attempts to reduce cluster cost by both removing un-needed nodes and down-sizing those\n  # that can't be removed.  Mutually exclusive with the ttlSecondsAfterEmpty parameter.\n  consolidation:\n    enabled: true\n  #sttlSecondsAfterEmpty: 60\n  requirements:\n    - key: karpenter.k8s.aws/instance-family\n      operator: NotIn\n      values:\n        - a1\n        - c1\n        - c3\n        - inf1\n        - t3\n        - t2\n    - key: karpenter.k8s.aws/instance-cpu\n      operator: Lt\n      values: \n        - \"33\"\n    - key: 'kubernetes.io/arch'\n      operator: In\n      values: ['amd64']\n    - key: karpenter.sh/capacity-type\n      operator: In\n      values: ['on-demand']\n      #values: ['on-demand', 'spot']\n  providerRef:\n    name: karpenter-default\n    tags:\n      karpenter.sh/cluster_name: eks-blueprint\n      karpenter.sh/provisioner: default\n  limits:\n    resources:\n      cpu: '200'\n  labels:\n    billing-team: default\n    team: default\n    type: karpenter\n  taints:\n    - key: karpenter\n      value: 'true'\n      effect: NoSchedule"] is not in for_each map)
  - resource "kubectl_manifest" "karpenter_provisioner" {
      - api_version             = "karpenter.sh/v1alpha5" -> null
      - apply_only              = false -> null
      - force_conflicts         = false -> null
      - force_new               = false -> null
      - id                      = "/apis/karpenter.sh/v1alpha5/provisioners/default" -> null
      - kind                    = "Provisioner" -> null
      - live_manifest_incluster = (sensitive value)
      - live_uid                = "44fe9527-0f7d-4413-aa16-c24e0e49a45a" -> null
      - name                    = "default" -> null
      - server_side_apply       = false -> null
      - uid                     = "44fe9527-0f7d-4413-aa16-c24e0e49a45a" -> null
      - validate_schema         = true -> null
      - wait_for_rollout        = true -> null
      - yaml_body               = (sensitive value)
      - yaml_body_parsed        = <<-EOT
            apiVersion: karpenter.sh/v1alpha5
            kind: Provisioner
            metadata:
              name: default
            spec:
              consolidation:
                enabled: true
              labels:
                billing-team: default
                team: default
                type: karpenter
              limits:
                resources:
                  cpu: "200"
              providerRef:
                name: karpenter-default
                tags:
                  karpenter.sh/cluster_name: eks-blueprint
                  karpenter.sh/provisioner: default
              requirements:
              - key: karpenter.k8s.aws/instance-family
                operator: NotIn
                values:
                - a1
                - c1
                - c3
                - inf1
                - t3
                - t2
              - key: karpenter.k8s.aws/instance-cpu
                operator: Lt
                values:
                - "33"
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                - on-demand
              taints:
              - effect: NoSchedule
                key: karpenter
                value: "true"
        EOT -> null
      - yaml_incluster          = (sensitive value)
    }
```
</details>

and then i will loose all my instances at once..
