### ISSUE TITLE
MNG with multiple volumes example

### ISSUE THREAD

**Issue by rothgar** [aws-ia/terraform-aws-eks-blueprints#1261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
An [example managed node group](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/node-groups/managed-node-groups/main.tf) with multiple EBS volumes attached. One volume for / and a separate volume mounted to /var/lib/containerd using AmazonLinux2.

#### Describe the solution you would like
Make it easy for users to use blueprints and map 2nd EBS volumes for containerd to avoid disk i/o contention and root drives filling up.

#### Describe alternatives you have considered
I have an example working with eksctl/cloudformation in documentation.
```
managedNodeGroups:
  - name: al2-workers
    amiFamily: AmazonLinux2
    desiredCapacity: 2
    volumeSize: 80
    additionalVolumes:
      - volumeName: '/dev/sdz'
        volumeSize: 100
    preBootstrapCommands:
      - "systemctl stop containerd"
      - "mkfs -t ext4 /dev/nvme1n1"
      - "rm -rf /var/lib/containerd/*"
      - "mount /dev/nvme1n1 /var/lib/containerd/"
      - "systemctl start containerd"
```

#### Additional context
This will be linked to from the EKS best practices guide because it is recommended that customers use separate volumes for / and containers
