### ISSUE TITLE
karpenter-cert is out of sync

### ISSUE THREAD

**Issue by krishanshamod** [aws-ia/terraform-aws-eks-blueprints#1340]
I added the Karpenter addon using ArgoCD. But it is an out of sync always because Karpenter adds extra data to the karpenter-cert secret which is not expected by ArgoCD. Here are the extra data that are not in the desired manifest. How can I fix this issue?

```
data:
  ca-cert.pem: ++++++++
  server-cert.pem: ++++++++
  server-key.pem: ++++++++
```
