### ISSUE TITLE
EKS Auto Mode Custom Node Pool Blueprint

### ISSUE THREAD

**Issue by emolitor** [aws-ia/terraform-aws-eks-blueprints#2059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

An example blueprint for creating an EKS Auto Mode Cluster with a Custom Node Pool. For instance showing how to enable Graviton and/or spot instances. The example should not use either of the built in node pools (general-purpose or system) as to show the necessary steps for manually creating the EC2 access-entry (which is only automatically created when using the built in node pools).

**Comment by MDBeudekerCN** [comment]
I now have something like this but I can't get it to work:

Default Nodeclass (with added tags)

```
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: default-nc
spec:
  ephemeralStorage:
    iops: 3000
    size: 80Gi
    throughput: 125
  networkPolicy: DefaultAllow
  networkPolicyEventLogs: Disabled
  role: eks-auto # change to the role created by eks auto
  securityGroupSelectorTerms: # make sure you tag your securitygroups
  - tags:
      cluster_securitygroup: cluster-sg
  - tags:
      node_securitygroup: node-sg
  subnetSelectorTerms: # make sure you tag your securitygroups
  - tags:
      aws-subnet : private
  tags:
    ManagedBy: eks-auto
    aws_region: eu-central-1
```

General nodepool with T series

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-nodepool
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 1000
  template:
    metadata: {}
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default-nc
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: eks.amazonaws.com/instance-category
        operator: In
        values:
        - t
        - m
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      terminationGracePeriod: 24h0m0s
```

Default System nodepool with taints

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: system-nodepool
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 1000
  template:
    metadata: {}
    spec:
      expireAfter: 336h
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default-nc
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: eks.amazonaws.com/instance-category
        operator: In
        values:
        - t
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      terminationGracePeriod: 24h0m0s
      taints:
      - effect: NoSchedule
        key: CriticalAddonsOnly
```
