### ISSUE TITLE
[QUESTION] service of type LoadBalancer wont get an external IP

### ISSUE THREAD

**Issue by dil-sthaens** [aws-ia/terraform-aws-eks-blueprints#404]
#### Please describe your quesiton here
Hello,

I am working with the examples/eks-cluster-with-new-vpc terraform deployment to get used to EKS and Terraform and test how it works and how you can deploy a production plattform into EKS.
Our application usually is deployed by using a gitops workflow (fluxcd) and that is working well. Our application has a ingress controller which is configured as service type loadbalancer so it should get an IP address but that doesn't work.

I read through a lot of documentation and came to the conclusion that the AWS Load Balancer Controller add-on should provide the required function when using this annotations for the service:

```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing 
```

But my service is still not get an external IP. I reset all changes I made in the examples/eks-cluster-with-new-vpc terraform deployment to ensure that the issue is not caused by any changes I did.
Afterwards I tried to deploy a sample application into the EKS cluster following this guide:
https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html
except of the fargate steps at the beginning but they should be optional shouldn't they?

Result was that also this example application is not getting an external IP. 
After digging more through the installation steps of the example I figured out where the error might be. In step 5 it is explained to examine the target groups in the Loadbalancing area of EC2 and there is the surprise: I dont have any target groups nor loadbalancers.

My question would be how am I able to get an external IP for a service I describe in this cluster? Or is the terraform example I am using working as expected an hasn't got such a functionality?
