### ISSUE TITLE
[ADDON] Windows node support

### ISSUE THREAD

**Issue by marciogmorales** [aws-ia/terraform-aws-eks-blueprints#461]
#### Is your feature request related to a problem? Please describe
No.

#### Describe the solution you'd like
Adding Windows worker node as a Self-Managed add-on.

#### Describe alternatives you've considered
No alternatives.

#### Additional context
Having a Self-Managed add-on such as:

```
// Self-managed Add-ons
        new blueprints.addons.WindowsSupport(),
```

To enable Windows Support a ConfigMap is needed to be added to the cluster: (VPC-Resource-Controller-ConfigMap):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: kube-system
data:
  enable-windows-ipam: "true"
```
