### ISSUE TITLE
[Bug]: Terraform and Helm fighting over `app.kubernetes.io/managed-by` tag with cluster-autoscaler (maybe others)

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#499]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

deec7d5caea47c06dea48fa616ad2c56e52c3cce

### What is your environment, configuration and the example used?

- Terraform version 1.1.7

I am installing the cluster-autoscaler like this:

```hcl
  enable_cluster_autoscaler           = true
  cluster_autoscaler_helm_config = {
    version          = "9.18.0"
    values           = [templatefile("${path.module}/helm_values/cluster-autoscaler-values.yaml.tftpl", {nodeSelector = local.primaryNodeSelector})]
  }
```

with this Helm values template:

```yaml
# See:
# https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml
#
# This is a template, so we can get values from terraform. 
#

nodeSelector: ${jsonencode({ for ns_key, ns_value in nodeSelector : ns_key => ns_value })}

extraArgs:
  aws-use-static-instance-list: true

rbac:
  serviceAccount:
    create: false

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 512Mi
```

and I see plans like this all the time.

```hcl
 # module.k8s-addons.module.cluster_autoscaler[0].module.helm_addon.module.irsa[0].kubernetes_service_account_v1.irsa[0] has changed
~ resource "kubernetes_service_account_v1" "irsa" {
        id                              = "kube-system/cluster-autoscaler-sa"
        # (2 unchanged attributes hidden)

      ~ metadata {
          ~ labels           = {
              + "app.kubernetes.io/instance"   = "cluster-autoscaler"
              ~ "app.kubernetes.io/managed-by" = "terraform-aws-eks-blueprints" -> "Helm"
              + "app.kubernetes.io/name"       = "aws-cluster-autoscaler"
              + "argocd.argoproj.io/instance"  = "cluster-autoscaler"
              + "helm.sh/chart"                = "cluster-autoscaler-9.15.0"
            }
            name             = "cluster-autoscaler-sa"
          ~ resource_version = "2528890" -> "2528899"
            # (4 unchanged attributes hidden)
        }

      + secret {
          + name = "cluster-autoscaler-sa-token-8ns47"
        }
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # module.k8s-addons.module.cluster_autoscaler[0].module.helm_addon.module.irsa[0].kubernetes_service_account_v1.irsa[0] will be updated in-place
~ resource "kubernetes_service_account_v1" "irsa" {
        id                              = "kube-system/cluster-autoscaler-sa"
        # (2 unchanged attributes hidden)

      ~ metadata {
          ~ labels           = {
              - "app.kubernetes.io/instance"   = "cluster-autoscaler" -> null
              ~ "app.kubernetes.io/managed-by" = "Helm" -> "terraform-aws-eks-blueprints"
              - "app.kubernetes.io/name"       = "aws-cluster-autoscaler" -> null
              - "argocd.argoproj.io/instance"  = "cluster-autoscaler" -> null
              - "helm.sh/chart"                = "cluster-autoscaler-9.15.0" -> null
            }
            name             = "cluster-autoscaler-sa"
            # (5 unchanged attributes hidden)
        }

      - secret {
          - name = "cluster-autoscaler-sa-token-8ns47" -> null
        }
    }
```

It appears that Terraform and Helm are fighting over the `app.kubernetes.io/managed-by` tag.

### What did you do and What did you see instead?

The 2 tools should not be fighting over the same tag. Most likely Terraform should not set this, or should ignore changes to it, but the change could possibly be made on the helm side as well.
