### ISSUE TITLE
[Bug]: Changing the ArgoCD values does not update the ArgoCD installation.

### ISSUE THREAD

**Issue by spkane** [aws-ia/terraform-aws-eks-blueprints#518]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

770d534c5d82efefd7219606aafeda74ca424400

### What is your environment, configuration and the example used?

Terraform version 1.1.7

```hcl
  argocd_helm_config = {
    version          = "4.5.4"
    values           = [templatefile(
      "${path.module}/helm_values/argocd-values.yaml.tftpl"
    )]
  }
```

### What did you do and What did you see instead?

Apply ArgoCD, and then update the values file. Argo is not updated.

Adding `force_update = true` appears to have worked in my case, but I am not sure if this is really ideal, and or safe in all cases.

Adding `reuse_values = true` or `reset_values = true` did not seem to help in my tests.

```hcl
  argocd_helm_config = {
    reuse_values     = true
    force_update     = true
    version          = "4.5.4"
    values           = [templatefile(
      "${path.module}/helm_values/argocd-values.yaml.tftpl",
      {
        nodeSelector = local.primaryNodeSelector
      }
    )]
  }
```

Is there a workflow here that I am missing? Do I have to update the chart version or something to make the `upgrade` happen more naturally? 

In this case, I don't want to use a new chart, just update the values and have them take.

**Comment by kcoleman731** [comment]
HI @spkane thanks for submitting the issue. I just tested this locally and it looks like value updates are applying correctly. Are you able to share your `argocd-values.yaml.tftpl` config and I can test your config on my side.

To try and repro your issue, I used the following:

```
  enable_argocd = true
  argocd_helm_config = {
    version = "4.5.4"
    values  = [templatefile("${path.module}/argo-values.yaml", {})]
  }
```

I copied the contents of the [default values file ](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/modules/kubernetes-addons/argocd/values.yaml)in the argocd module into `argo-values.yaml` and ran apply. I then bumped `sever.autoscaling.minReplicas` and `repoServer.autoscaling.minReplicas` to 3 and set `redis-ha.enabled` to false. Then ran apply again. You can see the plan output below. 

```
Terraform will perform the following actions:

  # module.kubernetes_addons.module.argocd[0].module.helm_addon.helm_release.addon[0] will be updated in-place
  ~ resource "helm_release" "addon" {
        id                         = "argo-cd"
        name                       = "argo-cd"
      ~ values                     = [
          - <<-EOT
                redis-ha:
                  enabled: true

                controller:
                  enableStatefulSet: true

                server:
                  autoscaling:
                    enabled: true
                    minReplicas: 2

                repoServer:
                  autoscaling:
                    enabled: true
                    minReplicas: 2
            EOT,
          + <<-EOT
                redis-ha:
                  enabled: false

                controller:
                  enableStatefulSet: true

                server:
                  autoscaling:
                    enabled: true
                    minReplicas: 3

                repoServer:
                  autoscaling:
                    enabled: true
                    minReplicas: 3
            EOT,
        ]
        # (27 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
