### ISSUE TITLE
[QUESTION] additional manifests not working

### ISSUE THREAD

**Issue by mattduguid** [aws-ia/terraform-aws-eks-blueprints#560]
We are looking to extend the default rights of an application_team.

We setup an "application_team" called "team-sm-reader",
```
# etc...
application_teams = {
    team-sm-reader = {
      "labels" = {
        # etc...
      }
      "quota" = {
        # etc...
      }
      manifests_dir = "./manifests/service-smreader"
      users = [
        "arn:aws:iam::${data.aws_caller_identity.current.account_id}:user/service-smreader", 
      ]
    }    
  }
# etc...
```

That automatically adds the following to the "aws-auth" configmap,
```
# etc...
- "groups":
  - "team-sm-reader-group"
  "rolearn": "arn:aws:iam::<ACCOUNT_ID>:role/aws-hsaap-poc-team-sm-reader-Access"
  "username": "team-sm-reader"
# etc...
```

To extend that application_team we have enabled the "manifests_dir" and added in the following to allow management of configmaps in their namespace,
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test
  namespace: team-sm-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "namespaces"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test
  namespace: team-sm-reader
subjects:
  - kind: Group
    name: team-sm-reader-group
    namespace: team-sm-reader
    apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test
```

We then set "AWS Access Key ID" + "AWS Secret Access Key" and assume the role,
```
aws eks --region ap-southeast-2 update-kubeconfig --name aws-hsaap-poc-eks --role-arn arn:aws:iam::<ACCOUNT_ID>:role/aws-hsaap-poc-team-sm-reader-Access
```

But we cannot create configmaps as expected, the error is,
```
kubectl apply -f ../_TEST/6_example_configmap.yaml                        
Error from server (Forbidden): error when creating "../_TEST/6_example_configmap.yaml": configmaps is forbidden: User "team-sm-reader" cannot create resource "configmaps" in API group "" in the namespace "team-sm-reader"
```
