### ISSUE TITLE
[QUESTION] Unable to use Nginx ingress on fargate

### ISSUE THREAD

**Issue by rohitjha941** [aws-ia/terraform-aws-eks-blueprints#607]
#### Please describe your question here
I am trying to run Nginx ingress on Fargate. I added the namespace of Nginx, but it seems that the load balancer is not registering the target. 

#### Additional context
Nginx Values YAML file
```
controller:
  service:
    externalTrafficPolicy: "Local"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
  config:
    proxy-real-ip-cidr: ${cidr}
  image:
    allowPrivilegeEscalation: false

```

#### More

- [x] Yes, I have checked the repo for existing issues before raising this question
