### ISSUE TITLE
[Bug]: When using Managed NG and Self-Managed NG, the Security Group does not allow Port 53 by default  

### ISSUE THREAD

**Issue by darrenlin** [aws-ia/terraform-aws-eks-blueprints#619]
### Welcome to Amazon EKS Blueprints!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/aws-ia/terraform-aws-eks-blueprints/issues) and didn't find any.

### Amazon EKS Blueprints Release version

4.0.9

### What is your environment, configuration and the example used?

I tried to create two node groups. One is managed node group, and another is self-managed node group (for local zones and outpost, but they are not required to reproduce the issue). 

I am using the example below. 

```
module "eks_blueprints" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints"

  # EKS CLUSTER
  cluster_version    = "1.22"
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets
  cluster_name       = local.cluster_name

  # EKS MANAGED NODE GROUPS
  managed_node_groups = {
    managed_ng = {
      node_group_name = "managed-ng"
      instance_types  = ["m5.large"]
      subnet_ids      = module.vpc.private_subnets

      min_size = 1
    }
  }

  self_managed_node_groups = {
    self_mg_5 = {
      node_group_name    = "self-managed-ondemand"
      launch_template_os = "amazonlinux2eks"
      subnet_ids         = module.vpc.private_subnets
      min_size = 1

    }
  }
}
```

### What did you do and What did you see instead?

I found that: 
- self-managed node groups uses "EKS node shared security group"  (sg-094ab4408afdddb9b)
- managed node groups uses "EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads." (sg-04f3aadaccae6341d)

```
➜  aws ec2 describe-security-groups --group-ids sg-094ab4408afdddb9b --query 'SecurityGroups[0].{Inbound:IpPermissions,Outbound:IpPermissionsEgress}' --output yaml
Inbound:
- FromPort: 10250
  IpProtocol: tcp
  IpRanges: []
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 10250
  UserIdGroupPairs:
  - Description: Cluster API to node kubelets
    GroupId: sg-09bfcd29517d60b58
    UserId: '091550601287'
- FromPort: 53
  IpProtocol: tcp
  IpRanges: []
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 53
  UserIdGroupPairs:
  - Description: Node to node CoreDNS
    GroupId: sg-094ab4408afdddb9b
    UserId: '091550601287'
- FromPort: 53
  IpProtocol: udp
  IpRanges: []
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 53
  UserIdGroupPairs:
  - Description: Node to node CoreDNS
    GroupId: sg-094ab4408afdddb9b
    UserId: '091550601287'
- FromPort: 443
  IpProtocol: tcp
  IpRanges: []
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 443
  UserIdGroupPairs:
  - Description: Cluster API to node groups
    GroupId: sg-09bfcd29517d60b58
    UserId: '091550601287'
Outbound:
- FromPort: 53
  IpProtocol: tcp
  IpRanges: []
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 53
  UserIdGroupPairs:
  - Description: Node to node CoreDNS
    GroupId: sg-094ab4408afdddb9b
    UserId: '091550601287'
- FromPort: 53
  IpProtocol: udp
  IpRanges: []
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 53
  UserIdGroupPairs:
  - Description: Node to node CoreDNS
    GroupId: sg-094ab4408afdddb9b
    UserId: '091550601287'
- FromPort: 123
  IpProtocol: udp
  IpRanges:
  - CidrIp: 0.0.0.0/0
    Description: Egress NTP/UDP to internet
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 123
  UserIdGroupPairs: []
- FromPort: 443
  IpProtocol: tcp
  IpRanges:
  - CidrIp: 0.0.0.0/0
    Description: Egress all HTTPS to internet
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 443
  UserIdGroupPairs:
  - Description: Node groups to cluster API
    GroupId: sg-09bfcd29517d60b58
    UserId: '091550601287'
- FromPort: 123
  IpProtocol: tcp
  IpRanges:
  - CidrIp: 0.0.0.0/0
    Description: Egress NTP/TCP to internet
  Ipv6Ranges: []
  PrefixListIds: []
  ToPort: 123
  UserIdGroupPairs: []
```

However, the security group rules does not allow UDP 53 data transfer, and will result errors for add-on installations and difficult to debug for new customers.
