### ISSUE TITLE
Help Needed :- How to get access to the argocd and other application using cluster IP or domain

### ISSUE THREAD

**Issue by ashutonara** [aws-ia/terraform-aws-eks-blueprints#861]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here
Hello All,

I am following this [example](https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-external-dns/main.tf) and pretty much I am able to provision everything.
`kubectl` command is working fine

## I got two questions:-
1. I am not able to reach to the argocd ( I can see the argod using `kubectl` and `port forwarding`) but I want to access the services / apps using `api.example.com` and `argocd.example.com` etc.

2. I thought the external dns, will create a record set but I can not see it . Am I missing anything? 

#### Provide a link to the example/module related to the question
nginx-values.yaml
```yaml
controller:
  service:
    type: LoadBalancer
    externalTrafficPolicy: "Local"
    annotations:
      # AWS Load Balancer Controller Annotations
      service.beta.kubernetes.io/aws-load-balancer-name: ${name}
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-subnets: ${public_subnets}
      service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
      service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: deregistration_delay.timeout_seconds=120
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-scheme-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=${environment},Team=${name}


      # SSL Annotations
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${ssl_cert_arn}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'

      # External DNS Annotations
      external-dns.alpha.kubernetes.io/hostname: ${hostname}

  targetPorts:
      http: http
      https: http
```

eks.tf
```tf
module "eks" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints"

  #region Cluster attrs
  cluster_name    = local.cluster_name
  cluster_version = "1.23"
  #endregion

  #region VPC attrs
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnets
  #endregion

  map_users = [{
    userarn  = "arn:aws:iam::<abcd>:user/ashutosh"
    username = "ashutosh"
    groups   = ["system:masters", "system:bootstrappers", "system:nodes"]
  }]


  enable_irsa                     = true
  cluster_endpoint_public_access  = true
  cluster_endpoint_private_access = true

  node_security_group_additional_rules = {
    ingress_allow_access_from_control_plane = {
      type                          = "ingress"
      protocol                      = "tcp"
      from_port                     = 9443
      to_port                       = 9443
      source_cluster_security_group = true
      description                   = "Allow access from control plane"
    }
  }

  #region MNG attrs
  managed_node_groups = {
    mg_5 = {
      node_group_name = "managed-ondemand"
      instance_types  = var.instance_types
      subnet_ids      = module.vpc.private_subnets

      desired_size = 3
      max_size     = 5
      min_size     = 2
    }
  }
  #endregion

  tags = local.tags
}

module "eks_kubernetes_addons" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints//modules/kubernetes-addons"

  eks_cluster_id       = module.eks.eks_cluster_id
  eks_cluster_endpoint = module.eks.eks_cluster_endpoint
  eks_oidc_provider    = module.eks.oidc_provider
  eks_cluster_version  = module.eks.eks_cluster_version
  eks_cluster_domain   = var.eks_cluster_domain

  enable_argocd = true
  # This example shows how to set default ArgoCD Admin Password using SecretsManager with Helm Chart set_sensitive values.
  argocd_helm_config = {
    set_sensitive = [
      {
        name  = "configs.secret.argocdServerAdminPassword"
        value = bcrypt(data.aws_secretsmanager_secret_version.admin_password_version.secret_string)
      }
    ]
  }

  argocd_manage_add_ons = true # Indicates that ArgoCD is responsible for managing/deploying add-ons
  argocd_applications = {
    workloads = {
      path     = "envs/dev"
      repo_url = "https://github.com/aws-samples/eks-blueprints-workloads.git"
      values = {
        spec = {
          ingress = {
            host = "eks.${var.eks_cluster_domain}"
          }
        }
      }
    }
  }

  enable_ingress_nginx = true
  ingress_nginx_helm_config = {
    values = [templatefile("${path.module}/nginx-values.yaml", {
      name           = local.cluster_name
      hostname       = var.eks_cluster_domain
      ssl_cert_arn   = data.aws_acm_certificate.issued.arn
      public_subnets = join(",", module.vpc.public_subnets)
      environment    = var.environment
    })]
  }

  enable_aws_load_balancer_controller = true
  enable_external_dns                 = true

  # Add-ons
  enable_amazon_eks_vpc_cni = true
  amazon_eks_vpc_cni_config = {
    addon_version     = data.aws_eks_addon_version.latest["vpc-cni"].version
    resolve_conflicts = "OVERWRITE"
  }

  enable_amazon_eks_coredns = true
  amazon_eks_coredns_config = {
    addon_version     = data.aws_eks_addon_version.latest["coredns"].version
    resolve_conflicts = "OVERWRITE"
  }

  enable_amazon_eks_kube_proxy = true
  amazon_eks_kube_proxy_config = {
    addon_version     = data.aws_eks_addon_version.default["kube-proxy"].version
    resolve_conflicts = "OVERWRITE"
  }

  enable_cert_manager       = true
  enable_cluster_autoscaler = true
  enable_metrics_server = true
  enable_argo_rollouts = true

  tags = local.tags
}
```

#### Additional context

Any help would be highly appreciated

**Comment by askulkarni2** [comment]
Hi @ashutonara, please refer to the [Ingress Configuration](https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/) of the ArgoCD documentation. You can also refer to our [external-dns](https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/examples/eks-cluster-with-external-dns) example which shows how to configure external-dns + nginx + lbc to configure complete ingress solution for a service.

**Comment by ashutonara** [comment]
The mentioned URL here is wrong https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/examples/eks-cluster-with-external-dns/main.tf#L81

**Comment by ashutonara** [comment]
The NLB is not getting created somehow. I can not see in aws.

```yaml
controller:
  service:
    type: LoadBalancer
    externalTrafficPolicy: "Local"
    annotations:
      # AWS Load Balancer Controller Annotations
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

      # SSL Annotations
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${ssl_cert_arn}
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'

      # External DNS Annotations
      external-dns.alpha.kubernetes.io/hostname: ${hostname}

  targetPorts:
      http: http
      https: http
```
