### ISSUE TITLE
create_launch_template breaks cluster DNS

### ISSUE THREAD

**Issue by vprus** [aws-ia/terraform-aws-eks-blueprints#962]
I have created an EKS cluster using the TF file at https://gist.github.com/vprus/b10a5d12f77abbaeba69650b0ca7b3a5.  It creates 
- Managed node group without create_launch_template; coredns gets scheduled there
- Managed node group with create_launch_template

Workload on the second group is unable to resolve cluster DNS names.

The problem seems to be with security groups. I have these security groups
- sg-0d423b7cc90f895d5 / eks-cluster-sg-analytics-2-803067819 (created by EKS, allows ingress from itself)
- sg-02cb5e34ce1e8625a / analytics-2-cluster-20220830085301105500000002 (created by terraform, customizable with cluster_security_group_additional_rules)
- sg-0cdccc699139076f9 / analytics-2-node-20220830085301103400000001 (created by terraform, customizable with node_security_group_additional_rules)

I then observe that
- node in the first nodegroup is associated with eks-cluster-sg-analytics-2-803067819 and only it (both the node and interfaces)
- node in the second nodegroup  is associated analytics-2-node-20220830085301103400000001

eks-cluster-sg-analytics-2-803067819 does not allow ingress from analytics-2-node-20220830085301103400000001, so DNS queries fail. Since node is not associated with analytics-2-cluster-20220830085301105500000002, I can't add additional rules in TF. I can add additional rules to eks-cluster-sg-analytics-2-803067819, and it fixes the problem, but I'd rather avoid manual tweaks.

Is there anything wrong in my TF file, or is this a bug?

**Comment by vprus** [comment]
FOAD, this is the test pod I use to test DNS
```
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: kafka
spec:
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: purpose
              operator: In
              values:
              - infra
  containers:
  - name: dnsutils
    image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
